### ISSUE TITLE
GMn replay script contains user-specific information

### ISSUE THREAD

**Issue by sebastianseeds** [provakar1994/jlab-HPC#6]
Minor issue. No observed impact to functionality.

`submit-gmn-jobs.sh` L:108 sets the `jobname` variable to `'pdatta_gmn_'$runnum'_segment'$i` which configures the name of the job on the farm. 

Ideally, the `jobname` should probably reflect the end-user.

**Comment by provakar1994** [comment]
Thank you for bringing this to my attention. I have made the necessary changes. The `jobname` will reflect the end-user instead of "pdatta" from now on (https://github.com/provakar1994/jlab-HPC/commit/7ebbfe8c7415f5548cddd87d5187e3a8968357a8). Be sure to pull the changes.

Btw, even though this script works I'd recommend using `sbs-replay-main.sh` script for replay purposes. It is the most up-to-date and works for all both GMn and GEn.
